#!/usr/bin/env bash
# IOWAP — node base entrypoint (T-119).
#
# Translates environment variables into the files the node stack reads from
# ~/.relay (relay_config.json, node.yaml, ai-relay-agent.json, token) and
# then execs the node-daemon (SSE, event-driven).
#
# Environment variables (all optional unless noted):
#   RELAY_URL          — relay base URL, e.g. https://relay.example.com (REQUIRED)
#   NODE_NAME          — human-friendly node name (default: container hostname)
#   NODE_PROFILE       — profile name to publish from /app/profiles/ (optional)
#   NODE_ROLE          — node role: "worker" (default) or "service"
#   NODE_ENDPOINT      — upstream endpoint for bridge-route upstream URLs
#   NODE_REGISTRATION_SECRET — pre-created registration secret (rs_...)
#   RELAY_HEARTBEAT_INTERVAL — overrides heartbeat_interval (seconds)
#   RELAY_CLAIM_INTERVAL     — overrides claim_interval (seconds)
#   RELAY_REQUEST_TIMEOUT    — overrides request_timeout (seconds)
#   RELAY_LOG_LEVEL          — log level (DEBUG/INFO/WARNING/ERROR)
#
# Idempotent: reuses existing meta + token on subsequent starts.

set -euo pipefail

RELAY_DIR="${HOME}/.relay"
CONFIG_JSON="${RELAY_DIR}/relay_config.json"
META_JSON="${RELAY_DIR}/ai-relay-agent.json"
TOKEN_FILE="${RELAY_DIR}/ai-relay-agent.token"
NODE_YAML="${RELAY_DIR}/node.yaml"

mkdir -p "${RELAY_DIR}"

# --- RELAY_URL: explicit env, else mDNS discovery -------------------------
if [ -z "${RELAY_URL:-}" ]; then
    echo "[entrypoint] RELAY_URL not set — attempting mDNS discovery..."
    DISCOVERED=$(python3 - <<'PY'
import sys
try:
    from iowap_node.relay_client import _discover_relay_mdns
    url = _discover_relay_mdns(timeout=3.0)
    if url:
        print(url)
except Exception as exc:
    print(f"mDNS discovery failed: {exc}", file=sys.stderr)
PY
    )
    if [ -n "${DISCOVERED}" ]; then
        RELAY_URL="${DISCOVERED}"
        export RELAY_URL
        echo "[entrypoint] mDNS discovered relay at ${RELAY_URL}"
    else
        echo "[entrypoint] ERROR: RELAY_URL is required and mDNS discovery found no relay." >&2
        exit 1
    fi
fi

BASE_URL="${RELAY_URL%/}"
NODE_NAME="${NODE_NAME:-$(hostname 2>/dev/null || echo node)}"
NODE_ROLE="${NODE_ROLE:-worker}"

# --- relay_config.json ----------------------------------------------------
cat > "${CONFIG_JSON}" <<EOF
{
  "base_url": "${BASE_URL}",
  "heartbeat_interval": ${RELAY_HEARTBEAT_INTERVAL:-8},
  "claim_interval": ${RELAY_CLAIM_INTERVAL:-5},
  "status_interval": 7200,
  "rt_refresh_before_seconds": 86400,
  "rs_refresh_before_seconds": 3600,
  "request_timeout": ${RELAY_REQUEST_TIMEOUT:-10},
  "task_timeout": 600,
  "log_level": "${RELAY_LOG_LEVEL:-INFO}"
}
EOF
echo "[entrypoint] relay_config.json written (base_url=${BASE_URL})"

# --- node.yaml -------------------------------------------------------------
if [ ! -f "${NODE_YAML}" ]; then
    cat > "${NODE_YAML}" <<EOF
# Auto-generated by iowap-docker/base entrypoint.
node_name: ${NODE_NAME}
EOF
    echo "[entrypoint] node.yaml seeded (node_name=${NODE_NAME})"
fi

if [ -n "${NODE_PROFILE:-}" ]; then
    IMAGE_PROFILES_DIR="/app/profiles"
    PROFILE_FILE=""
    if [ -f "${IMAGE_PROFILES_DIR}/${NODE_PROFILE}" ]; then
        PROFILE_FILE="${IMAGE_PROFILES_DIR}/${NODE_PROFILE}"
    elif [ -f "${IMAGE_PROFILES_DIR}/${NODE_PROFILE}.yaml" ]; then
        PROFILE_FILE="${IMAGE_PROFILES_DIR}/${NODE_PROFILE}.yaml"
    elif [ -f "${IMAGE_PROFILES_DIR}/${NODE_PROFILE}.yml" ]; then
        PROFILE_FILE="${IMAGE_PROFILES_DIR}/${NODE_PROFILE}.yml"
    else
        echo "[entrypoint] ERROR: NODE_PROFILE='${NODE_PROFILE}' not found in ${IMAGE_PROFILES_DIR}" >&2
        exit 1
    fi
    cp "${PROFILE_FILE}" "${NODE_YAML}"
    echo "[entrypoint] node.yaml published from profile '${NODE_PROFILE}' (${PROFILE_FILE})"
fi

# --- first-start registration ---------------------------------------------
if [ ! -f "${META_JSON}" ]; then
    echo "[entrypoint] no metadata found — registering node '${NODE_NAME}' with relay"

    REGISTER_PAYLOAD=$(python3 - <<'PY'
import json, os, yaml
caps = []
node_yaml = os.path.expanduser("~/.relay/node.yaml")
try:
    with open(node_yaml) as f:
        prof = yaml.safe_load(f) or {}
    caps = prof.get("capabilities", []) or []
except Exception:
    pass
clean = []
for c in caps:
    if isinstance(c, dict) and "name" in c:
        clean.append({"name": c["name"], "version": str(c.get("version", "1.0.0"))})
print(json.dumps({
    "node_name": os.environ.get("NODE_NAME", "node"),
    "endpoint": os.environ.get("NODE_ENDPOINT") or None,
    "capabilities": clean,
    "role": os.environ.get("NODE_ROLE", "worker"),
}))
PY
    )
    REGISTER_PAYLOAD_FILE="${RELAY_DIR}/register-payload.json"
    printf '%s' "${REGISTER_PAYLOAD}" > "${REGISTER_PAYLOAD_FILE}"
    python3 - <<PY
import json, os, sys
import httpx
base_url = os.environ["RELAY_URL"].rstrip("/")
with open(os.path.expanduser("~/.relay/register-payload.json")) as f:
    payload = json.load(f)
headers = {}
secret = os.environ.get("NODE_REGISTRATION_SECRET")
if secret:
    headers["X-Registration-Secret"] = secret
try:
    r = httpx.post(f"{base_url}/relay/v2/auth/register", json=payload, headers=headers, timeout=30)
    r.raise_for_status()
except httpx.HTTPError as exc:
    print(f"[entrypoint] ERROR: registration failed: {exc}", file=sys.stderr)
    sys.exit(1)
data = r.json()
meta = {
    "base_url": base_url,
    "node_id": data["node_id"],
    "node_name": data.get("node_name", payload["node_name"]),
    "registration_secret": data.get("registration_secret"),
    "capabilities": payload["capabilities"],
}
rel = os.path.expanduser("~/.relay")
import pathlib
pathlib.Path(rel).mkdir(parents=True, exist_ok=True)
pathlib.Path(rel, "ai-relay-agent.json").write_text(json.dumps(meta, indent=2))
os.chmod(os.path.join(rel, "ai-relay-agent.json"), 0o600)
token = data.get("token")
if token:
    token_path = pathlib.Path(rel, "ai-relay-agent.token")
    token_path.write_text(json.dumps({"token": token, "expires_at": None}) + "\n")
    os.chmod(token_path, 0o600)
status = data.get("status", "pending")
print(f"[entrypoint] registered node_id={data['node_id']} status={status}")
if status == "pending":
    print("[entrypoint] node is pending approval — approve it via dashboard or admin API")
PY
    rm -f "${REGISTER_PAYLOAD_FILE}"
else
    echo "[entrypoint] reusing existing metadata (${META_JSON})"
fi

exec "$@"